---
- name: Update and Upgrade Ubuntu Servers
  hosts: all
  become: yes

  tasks:
    - name: Update apt package lists
      apt:
        update_cache: yes
      when: "ansible_pkg_mgr == 'apt'"   

    - name: Upgrade all packages in ubuntu server
      apt:
        upgrade: yes
      when: "ansible_pkg_mgr == 'apt'"

    - name: update the package in Redhat 9 servers
      dnf:
        name: '*'
        state: latest
      when: "ansible_pkg_mgr == 'dnf'"

    - name: update the package in Redhat 8 or lesser versions
      yum:
        name: '*'
        state: latest
      when: "ansible_pkg_mgr == 'yum'"

